spring:
  datasource:
    username: root
    password: your password
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

# mybatis
mybatis:
  type-aliases-package: com.ldy.myblog.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml

# mybatis log
logging:
  level:
    com:
      ldy:
        myblog:
          mapper: info
server:
  port: 8082
